name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-checks:
    name: Static & Dependency Security Scans
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pip-audit
      run: |
        pip install pip-audit
        pip-audit || echo "PIP Audit failed, continuing anyway"

    - name: Run Safety (local scan, no API)
      uses: pyupio/safety-action@v1
      continue-on-error: true
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}
    
    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r . || true

    - name: Run Semgrep
      run: |
        curl -sL https://semgrep.dev/install.sh | sh
        ./semgrep/semgrep --config auto --exclude .venv || true

  test:
    name: Run Tests
    needs: security-checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest
